### ISSUE TITLE
Python 3.10 support

### ISSUE THREAD

**Issue by blayzen-w** [dstegelman/python-usps#6]
It looks like this does not work with python 3.10. It raises an `AttributeError 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'`. This seems to be caused by the deprecation and removal of the ElementTree.getchindren function (deprecated in 3.2, removed in 3.9)

See https://docs.python.org/3.8/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.getchildren

**Comment by blayzen-w** [comment]
It looks like a lot of the unit tests are failing due to the USPS api requiring the data to be submitted in an exact order. I'm going to do a bit of a rewrite to fix the problems and get things up to date. I hopefully should have a PR up soon. If you need help maintaining the project, I'm happy to help.

**Comment by blayzen-w** [comment]
I setup github actions on our fork. Let me know if you want those too and I can open a pull request. It just requires you to add a repository secret for the USPS access key to work.
